import json
import requests
import os

class FrameDialogueManager:
    def __init__(self, prompt_path="frame_prompt.txt", ollama_model="gemma3:latest", ollama_url="http://localhost:11434/api/chat"):
        self.model = ollama_model
        self.ollama_url = ollama_url
        
        # Load the system prompt we just created
        if os.path.exists(prompt_path):
            with open(prompt_path, "r", encoding="utf-8") as f:
                self.system_prompt = f.read()
        else:
            self.system_prompt = "You are a helpful assistant."
            
        # The conversation memory tracking current state
        self.conversation_history = [
            {"role": "system", "content": self.system_prompt}
        ]
        
    def handle_message(self, user_message: str):
        # 1. Append user's message to history
        self.conversation_history.append({"role": "user", "content": user_message})
        
        # 2. Call Ollama (we strongly suggest JSON format via prompt)
        payload = {
            "model": self.model,
            "messages": self.conversation_history,
            "stream": False,
            "format": "json" # Force JSON output if your Ollama version supports it
        }
        
        try:
            response = requests.post(self.ollama_url, json=payload)
            
            if response.status_code != 200:
                return {"error": f"HTTP {response.status_code}", "details": response.text}
                
            data = response.json()
            
            ai_content = data.get("message", {}).get("content", "")
            
            # 3. Append AI response back to history
            self.conversation_history.append({"role": "assistant", "content": ai_content})
            
            # 4. Parse JSON state
            try:
                state_data = json.loads(ai_content)
                return state_data
            except json.JSONDecodeError:
                # Fallback if the LLM didn't return perfect JSON
                return {"error": "Invalid JSON returned", "raw_content": ai_content}
                
        except Exception as e:
            return {"error": str(e)}

if __name__ == "__main__":
    # Simple test loop
    manager = FrameDialogueManager(ollama_model="gemma3:latest")
    print("Frame Dialogue Manager Initialized. (Type 'exit' to quit)")
    
    # Trigger the first greeting from the chatbot
    print("\n[Initializing...] Bot is typing...")
    initial_result = manager.handle_message("Please start the conversation by following the greeting frame.")
    if "error" not in initial_result:
        print("\nBot:", initial_result.get("agent_response", "<No response generated by LLM>"))
        print("\n[Internal Frame State]")
        print(json.dumps({
            "active_frame": initial_result.get("active_frame"),
            "filled_slots": initial_result.get("filled_slots"),
            "next_frame": initial_result.get("next_frame")
        }, indent=2))
        print("-" * 40)
    
    while True:
        try:
            user_input = input("You: ")
        except (EOFError, KeyboardInterrupt):
            print("\nExiting chat.")
            break
            
        if user_input.lower() in ['exit', 'quit']:
            break
            
        print("\n--- Sending to LLM ---")
        # To show what the LLM receives:
        print(json.dumps(manager.conversation_history[-1], indent=2))
            
        result = manager.handle_message(user_input)
        
        if "error" in result:
            print("\n[Error]")
            print(json.dumps(result, indent=2))
        else:
            print("\nBot:", result.get("agent_response", "<No response generated by LLM>"))
            print("\n[Internal Frame State]")
            state_dict = {
                "active_frame": result.get("active_frame"),
                "filled_slots": result.get("filled_slots"),
                "next_frame": result.get("next_frame")
            }
            print(json.dumps(state_dict, indent=2))
            
        print("-" * 40)
